name: compile

on:
  push:
    branches:
      - master
      - main

env:
  LATEX_ROOT_ITA: curriculum-vitae-ita
  LATEX_ROOT_ENG: curriculum-vitae-eng

jobs:
  Setup-Compile-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DanySK/compile-and-publish-all-latex@1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
