name: compile

on:
  push:
    branches:
      - master
      - main

env:
  LATEX_ROOT_ITA: curriculum-vitae-ita
  LATEX_ROOT_ENG: curriculum-vitae-eng

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Build latex ita
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.LATEX_ROOT_ITA }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Build latex eng
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.LATEX_ROOT_ENG }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
        
      - name: Bump version
        id: bump-version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          
      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%dT%H%M%S')"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}'
          
      - name: Upload CV ita
        id: upload-release-asset-ita
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.LATEX_ROOT_ITA }}.pdf
          asset_name: ${{ env.LATEX_ROOT_ITA }}-${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}.pdf
          asset_content_type: application/pdf

      - name: Upload CV eng
        id: upload-release-asset-eng
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.LATEX_ROOT_ENG }}.pdf
          asset_name: ${{ env.LATEX_ROOT_ENG }}-${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}.pdf
          asset_content_type: application/pdf
